name: Eleventy Build
on:
  push:
  pull_request:

env:
  NODE_VERSION: '20'

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version:  ${{ env.NODE_VERSION }}

      - name: Install packages
        run: npm ci

      - name: Run npm build
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./public

  publish:
    name: Publish site
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4

      - name: Download Pages artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
