name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20']

    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: public
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
